import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

//  Import des objets

import NavBar from '../components/NavBar'
import Footer from '../components/Footer'

//  Import des constantes

import NavLinks from "../constantes/NavLinks"
import FootLinks from "../constantes/FootLinks"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Alexandria</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar elements={NavLinks()}/>

      <div className={`min-h-screen`}>

        <p></p>

      </div>

      <Footer elements={FootLinks()}/>

    </div>
  )
}
