export default function BooksStatik() {
    return ([
        {title:"Akira", serie:true, tome:2, imgsrc:"/img/books/book-1.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5129563", },
        {title:"Akira", serie:true, tome:6, imgsrc:"/img/books/book-2.jpeg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"4129563", },
        {title:"Akira", serie:true, tome:3, imgsrc:"/img/books/book-3.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5123563", },
        {title:"Akira", serie:true, tome:1, imgsrc:"/img/books/book-4.jpg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"5129523", },
        {title:"Investir dans l'immobilier", serie:false, tome:1, imgsrc:"/img/books/book-5.jpeg", author:"Cédric Sernier", note:"2.0", editeur:"", isbn:"", sku:"5119563", },
        {title:"La brume des bois", tome:1, serie:false, imgsrc:"/img/books/book-6.webp", author:"J. Poulon", note:"3.0", editeur:"", isbn:"", sku:"5120563", },
        {title:"Punk 57", tome:1, serie:false, imgsrc:"/img/books/book-7.jpg", author:"Penelope Douglas", note:"5.0", editeur:"", isbn:"", sku:"5129963", },
        {title:"Le Hobbit", tome:1, serie:false, imgsrc:"/img/books/book-8.jpg", author:"J.R.R. Tolkien", note:"5.0", editeur:"", isbn:"", sku:"5189563", },
        {title:"Dark Romance", tome:1, serie:false, imgsrc:"/img/books/book-9.jpg", author:"Penelope Douglas", note:"4.0", editeur:"", isbn:"", sku:"5129763",  },
        {title:"Akira", serie:true, tome:2, imgsrc:"/img/books/book-1.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5129563", },
        {title:"Akira", serie:true, tome:6, imgsrc:"/img/books/book-2.jpeg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"4129563", },
        {title:"Akira", serie:true, tome:3, imgsrc:"/img/books/book-3.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5123563", },
        {title:"Akira", serie:true, tome:1, imgsrc:"/img/books/book-4.jpg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"5129523", },
        {title:"Investir dans l'immobilier", serie:false, tome:1, imgsrc:"/img/books/book-5.jpeg", author:"Cédric Sernier", note:"2.0", editeur:"", isbn:"", sku:"5119563", },
        {title:"La brume des bois", tome:1, serie:false, imgsrc:"/img/books/book-6.webp", author:"J. Poulon", note:"3.0", editeur:"", isbn:"", sku:"5120563", },
        {title:"Punk 57", tome:1, serie:false, imgsrc:"/img/books/book-7.jpg", author:"Penelope Douglas", note:"5.0", editeur:"", isbn:"", sku:"5129963", },
        {title:"Le Hobbit", tome:1, serie:false, imgsrc:"/img/books/book-8.jpg", author:"J.R.R. Tolkien", note:"5.0", editeur:"", isbn:"", sku:"5189563", },
        {title:"Dark Romance", tome:1, serie:false, imgsrc:"/img/books/book-9.jpg", author:"Penelope Douglas", note:"4.0", editeur:"", isbn:"", sku:"5129763",  },
        {title:"Akira", serie:true, tome:2, imgsrc:"/img/books/book-1.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5129563", },
        {title:"Akira", serie:true, tome:6, imgsrc:"/img/books/book-2.jpeg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"4129563", },
        {title:"Akira", serie:true, tome:3, imgsrc:"/img/books/book-3.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5123563", },
        {title:"Akira", serie:true, tome:1, imgsrc:"/img/books/book-4.jpg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"5129523", },
        {title:"Investir dans l'immobilier", serie:false, tome:1, imgsrc:"/img/books/book-5.jpeg", author:"Cédric Sernier", note:"2.0", editeur:"", isbn:"", sku:"5119563", },
        {title:"La brume des bois", tome:1, serie:false, imgsrc:"/img/books/book-6.webp", author:"J. Poulon", note:"3.0", editeur:"", isbn:"", sku:"5120563", },
        {title:"Punk 57", tome:1, serie:false, imgsrc:"/img/books/book-7.jpg", author:"Penelope Douglas", note:"5.0", editeur:"", isbn:"", sku:"5129963", },
        {title:"Le Hobbit", tome:1, serie:false, imgsrc:"/img/books/book-8.jpg", author:"J.R.R. Tolkien", note:"5.0", editeur:"", isbn:"", sku:"5189563", },
        {title:"Dark Romance", tome:1, serie:false, imgsrc:"/img/books/book-9.jpg", author:"Penelope Douglas", note:"4.0", editeur:"", isbn:"", sku:"5129763",  },
        {title:"Akira", serie:true, tome:2, imgsrc:"/img/books/book-1.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5129563", },
        {title:"Akira", serie:true, tome:6, imgsrc:"/img/books/book-2.jpeg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"4129563", },
        {title:"Akira", serie:true, tome:3, imgsrc:"/img/books/book-3.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5123563", },
        {title:"Akira", serie:true, tome:1, imgsrc:"/img/books/book-4.jpg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"5129523", },
        {title:"Investir dans l'immobilier", serie:false, tome:1, imgsrc:"/img/books/book-5.jpeg", author:"Cédric Sernier", note:"2.0", editeur:"", isbn:"", sku:"5119563", },
        {title:"La brume des bois", tome:1, serie:false, imgsrc:"/img/books/book-6.webp", author:"J. Poulon", note:"3.0", editeur:"", isbn:"", sku:"5120563", },
        {title:"Punk 57", tome:1, serie:false, imgsrc:"/img/books/book-7.jpg", author:"Penelope Douglas", note:"5.0", editeur:"", isbn:"", sku:"5129963", },
        {title:"Le Hobbit", tome:1, serie:false, imgsrc:"/img/books/book-8.jpg", author:"J.R.R. Tolkien", note:"5.0", editeur:"", isbn:"", sku:"5189563", },
        {title:"Dark Romance", tome:1, serie:false, imgsrc:"/img/books/book-9.jpg", author:"Penelope Douglas", note:"4.0", editeur:"", isbn:"", sku:"5129763",  },
        {title:"Akira", serie:true, tome:2, imgsrc:"/img/books/book-1.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5129563", },
        {title:"Akira", serie:true, tome:6, imgsrc:"/img/books/book-2.jpeg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"4129563", },
        {title:"Akira", serie:true, tome:3, imgsrc:"/img/books/book-3.jpg", author:"Katsuhiro Otomo", note:"4.0", editeur:"", isbn:"", sku:"5123563", },
        {title:"Akira", serie:true, tome:1, imgsrc:"/img/books/book-4.jpg", author:"Katsuhiro Otomo", note:"5.0", editeur:"", isbn:"", sku:"5129523", },
        {title:"Investir dans l'immobilier", serie:false, tome:1, imgsrc:"/img/books/book-5.jpeg", author:"Cédric Sernier", note:"2.0", editeur:"", isbn:"", sku:"5119563", },
        {title:"La brume des bois", tome:1, serie:false, imgsrc:"/img/books/book-6.webp", author:"J. Poulon", note:"3.0", editeur:"", isbn:"", sku:"5120563", },
        {title:"Punk 57", tome:1, serie:false, imgsrc:"/img/books/book-7.jpg", author:"Penelope Douglas", note:"5.0", editeur:"", isbn:"", sku:"5129963", },
        {title:"Le Hobbit", tome:1, serie:false, imgsrc:"/img/books/book-8.jpg", author:"J.R.R. Tolkien", note:"5.0", editeur:"", isbn:"", sku:"5189563", },
        {title:"Dark Romance", tome:1, serie:false, imgsrc:"/img/books/book-9.jpg", author:"Penelope Douglas", note:"4.0", editeur:"", isbn:"", sku:"5129763",  },
    ])
}